### ISSUE TITLE
Example in README.md does not work

### ISSUE THREAD

**Issue by fpauser** [ghempton/ember-routemanager#1]
Besides a few js-typos the routing does not work as soon as a substate is involved.

**Comment by ghempton** [comment]
The read me was thrown together in a few minutes when I first put this project together. I will get around to some detailed documentation eventually.

By substate do you mean a nested view state?

**Comment by fpauser** [comment]
Yes, substate == nested view state

**Comment by ghempton** [comment]
Nested view states aren't a supported feature of Ember. I created another library to accomodate that: [Ember Layout](https://github.com/ghempton/ember-layout).

**Comment by fpauser** [comment]
I meant an Em.ViewState with a sub Em.State - is that what you mean with "nested view state"?

Btw: I just discovered that ember has layout-support built in now:

https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/views/view.js#L85
https://github.com/emberjs/ember.js/blob/master/packages/ember-views/tests/views/view/layout_test.js
https://github.com/emberjs/ember.js/blob/master/packages/ember-handlebars/lib/helpers/yield.js
https://github.com/emberjs/ember.js/blob/master/packages/ember-handlebars/tests/helpers/yield_test.js

Might be a good idea to "merge" your Ember-Layout functionality right into ember.js, what do you think?

**Comment by ghempton** [comment]
Yeah I switched up ember-layout to not conflict with core, but I don't think it's ready to be merged quite yet.

The {{yield}} helper in ember core is just for subclassing views. Mine is for dynamic view replacement. To accomodate this difference I renamed the ember-layout helper to {{dynamicView}}.

**Comment by ghempton** [comment]
BTW, an Em.ViewState with a sub Em.State should work. Got a code sample? (or even better a jsfiddle)

**Comment by fpauser** [comment]
Here a slightly updated example demonstrating the not-working substate: http://jsbin.com/uhahuc/11/edit#html,live
Just comment-in the `show: Em.State.create({})` block to see what I mean.

**Comment by ghempton** [comment]
This issue with that example is that routes can only map to leaf nodes. You could put an 'index' state without a route next to the 'show' state.

State's that don't have routes defined are automatically traversed when the route is being resolved.

**Comment by fpauser** [comment]
Updated the example again: http://jsbin.com/uhahuc/16/edit#javascript,html,live

Although it is a bit misleading that routes can only map to leaf-nodes...

**Comment by ghempton** [comment]
The example appears to work for me. Is there still an issue?

**Comment by fpauser** [comment]
see #3
