### ISSUE TITLE
StateManager

### ISSUE THREAD

**Issue by juggy** [ghempton/ember-routemanager#4]
Hello,

With the current Head version of the StateManager, once you enter a state with a dynamic route  you get stuck in this state when you want to reenter it with different routing parameters.

```
Section: Ember.State.create
    route: "sections/:id"
    initialState: "Description"

    # Substates      
    Description: Ember.ViewState.create
      route: "description"
      view: S.views.QuoteSectionView.extend({contentBinding: "S.controllers.quoteController.selectedSection"})
   #....
```

If I change the location to "section/123" record 123 with show up, but then if I change the location to "section/234" it will still show record 123 and the StateManager will not change state whatsoever.

Thanks,
Julien.

**Comment by ghempton** [comment]
This should work and I use it in my own app. I also have a [test case](https://github.com/ghempton/ember-routemanager/blob/master/packages/ember-routemanager/tests/route_manager_test.js#L307) for it. Could you share a little bit more of the code or throw a jsfiddle up?

**Comment by juggy** [comment]
It seems related to another issue in Ember ... I got it to work after entering this. So let me close this.
